name: Generate Snake  

on:  
  schedule:  
    - cron: "0 0 * * *" # Runs once daily  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: Platane/snk@master  
        with:  
          github_user_name: devesh-rawat  
          svg_out_path: dist/github-contribution-grid-snake.svg  

      - name: Push Snake Animation  
        uses: peaceiris/actions-gh-pages@v3  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_branch: output  
          publish_dir: ./dist  
